### ISSUE TITLE
New scriptAction value GUI_INSTALL

### ISSUE THREAD

**Issue by herrfrei** [kwindrem/RpiDisplaySetup#29]
I'd like to detect if installation is started from command line or GUI. 

Background: For GUI install, default values should be applied while on command line the user is asked for values.

**Comment by kwindrem** [comment]
SetupHelper differentiates between an install and a reinstall. When the script is run from the command line with no options, a menu of choices is presented. One if these options is reinstall which will use the existing options set in a previous run. If the options have not been set then the reinstall option does not apply.

When reinstallMods or PackageManager calls the setup script is includes 'reinstall' or 'install' or 'uninstall' on the command line. This  causes SetupHelper to skip the user prompting. If options have been set (or are not required) then setup proceeds, otherwise the setup script exits without installing.

Are you creating a package? If so, let me know if I can help.

If you are just trying to reinstall the package from the command line, then including install on the command line will skip the prompting, or you can select reinstall (r) at the prompt.
